name: Understand close vs merge
on:
  pull_request:
    types: [closed]

jobs:
  echo-context-values:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        run: |
          echo "${{github.event.pull_request.base.sha}}"
          echo "${{github.sha}}"
