name: 'Understand close vs merge'
on:
  pull_request:
    types: [closed]

jobs:
  changes:
    runs-on: ubuntu-latest

    - name: github context
      run: |
        echo "${{github.event.pull_request.base.sha}}"
        echo "${{github.sha}}"
      

    
