name: 'Cleanup'
on:
  pull_request:
    types: [closed]

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            a:
              - packages/a/**
            b:
              - packages/b/**

  do-stuff-for-a:
    runs-on: ubuntu-latest
    needs: changes
    if: contains(needs.changes.outputs.packages, 'a')

    steps:
      - run: echo 'do-stuff-for-a ran'
